### ISSUE TITLE
Use the Mojo Executor to invoke Maven plugins

### ISSUE THREAD

**Issue by raehalme** [aleksandr-m/gitflow-maven-plugin#31]
I'm having hard time using this plugin on Linux because the `mvn` commands fail. Not really sure what's the problem. For some reason my environment doesn't like the `mvn groupId:artifactId:goal` syntax used to invoke the goals.

Anyways I decided to see if replacing the `mvn` calls with [the Mojo Executor](https://github.com/TimMoore/mojo-executor) would give better results, and it did! If I send you a PR replacing the use of `executeMvnCommand` method, would you be interested in reviewing it?

**Comment by aleksandr-m** [comment]
PR-s are welcome!
But, currently there is only one maven plugin call. Are you referring to `versions-maven-plugin` plugin?
Can you provide more details about when/how it fails?

**Comment by raehalme** [comment]
Here's is the error I get when executing `mvn gitflow:release-start` using version 1.3.1 of the plugin:

```
...
[INFO] Updating version(s) to '1.9'.
[DEBUG] mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=1.9 -DgenerateBackupPoms=false
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.434 s
[INFO] Finished at: 2017-02-02T21:39:56+02:00
[INFO] Final Memory: 16M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.3.1:release-start (default-cli) on project lvisnet-productcatalog-integration: /bin/sh: scl: line 1: syntax error: unexpected end of file
[ERROR] /bin/sh: error importing function definition for `BASH_FUNC_scl'
[ERROR] /bin/sh: scl: line 1: syntax error: unexpected end of file
[ERROR] /bin/sh: error importing function definition for `BASH_FUNC_scl'
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.3.1:release-start (default-cli) on project lvisnet-productcatalog-integration: /bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: /bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'
/bin/sh: scl: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_scl'

	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeCommand(AbstractGitFlowMojo.java:744)
	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeMvnCommand(AbstractGitFlowMojo.java:694)
	at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.mvnSetVersions(AbstractGitFlowMojo.java:609)
	at com.amashchenko.maven.plugin.gitflow.GitFlowReleaseStartMojo.execute(GitFlowReleaseStartMojo.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

By using the Mojo Executor the overhead of starting a new process can also be avoided.

**Comment by aleksandr-m** [comment]
@raehalme Some environmental issues maybe? It is running without problems on Ubuntu and Raspbian for me.

See https://github.com/xonsh/xonsh/issues/208 and https://github.com/AtomLinter/linter-puppet-lint/issues/68.

**Comment by raehalme** [comment]
@aleksandr-m I managed to get pass the `BASH_FUNC_scl` error by removing the `scl-utils` package and invoking `unset scl` before running Maven. Thanks for the tip!

Unfortunately the original problem remains and Maven complains about the `versions` plugin not being found:

```
[ERROR] [ERROR] Unable to resolve plugin for prefix: org.codehaus.mojo: No plugin found for prefix 'org.codehaus.mojo' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/thomas/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

**Comment by aleksandr-m** [comment]
@raehalme Using `gitflow-helper-maven-plugin`? :)

If yes, then take a look at [`MojoDescriptorCreator#getMojoDescriptor`](https://maven.apache.org/ref/3.3.1/xref/org/apache/maven/lifecycle/internal/MojoDescriptorCreator.html#L141) where `findPluginForPrefix` is used. It is a bit more complex than in [`gitflow-helper-maven-plugin`](https://github.com/egineering-llc/gitflow-helper-maven-plugin/blob/master/src/main/java/com/e_gineering/maven/gitflowhelper/MasterPromoteExtension.java#L66).

**Comment by raehalme** [comment]
@aleksandr-m Yes, I am :-) And now that you mentioned it it's possible that `gitflow-helper-maven-plugin` disables the plugin. 

I guess I never tested it on some other project besides the one I use for debugging which has both `gitflow-maven-plugin` and `gitflow-helper-maven-plugin` configured (and the `-X`  is not passed on to the new `mvn` process, ehem :-).

**Comment by random-dwi** [comment]
I am facing a similar issue on Fedora 33 and plugin version 1.15.1. It happens always when the plugin tries to execute a command:

```
[ERROR] Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.15.1:hotfix-finish (default-cli) on project: hotfix-finish: /bin/sh: _module_raw: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
[ERROR] /bin/sh: Fehler beim Importieren der Funktionsdefinition für `_module_raw'.
[ERROR] /bin/sh: switchml: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
[ERROR] /bin/sh: Fehler beim Importieren der Funktionsdefinition für `switchml'.
[ERROR] /bin/sh: switchml: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
[ERROR] /bin/sh: Fehler beim Importieren der Funktionsdefinition für `switchml'.
[ERROR] /bin/sh: _module_raw: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
[ERROR] /bin/sh: Fehler beim Importieren der Funktionsdefinition für `_module_raw'.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.amashchenko.maven.plugin:gitflow-maven-plugin:1.15.1:hotfix-finish (default-cli) on project: hotfix-finish
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
...
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoFailureException: hotfix-finish
    at com.amashchenko.maven.plugin.gitflow.GitFlowHotfixFinishMojo.execute (GitFlowHotfixFinishMojo.java:357)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
...
Caused by: org.apache.maven.plugin.MojoFailureException: /bin/sh: _module_raw: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/sh: Fehler beim Importieren der Funktionsdefinition für `_module_raw'.
/bin/sh: switchml: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/sh: Fehler beim Importieren der Funktionsdefinition für `switchml'.
/bin/sh: switchml: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/sh: Fehler beim Importieren der Funktionsdefinition für `switchml'.
/bin/sh: _module_raw: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.
/bin/sh: Fehler beim Importieren der Funktionsdefinition für `_module_raw'.

    at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeCommand (AbstractGitFlowMojo.java:1184)
    at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.executeMvnCommand (AbstractGitFlowMojo.java:1126)
    at com.amashchenko.maven.plugin.gitflow.AbstractGitFlowMojo.mvnCleanTest (AbstractGitFlowMojo.java:1045)
    at com.amashchenko.maven.plugin.gitflow.GitFlowHotfixFinishMojo.execute (GitFlowHotfixFinishMojo.java:184)
```

I could work around the issue be removing `environment-modules`:
```
sudo dnf remove environment-modules.x86_64
```
